### PR TITLE
Read body based on Content-Length header

### PR DESCRIPTION
**Pull request by rmweiss**
This code reads the message body based on the size specified in the "Content-Length" header. 

I do this in a loop, because in my tests "read" sometimes returned multiple result with length of 0 before the body was finally fetched.

### CODE REVIEW

**Comment by Drolla** [comment]
Hi Rmweiss and Geballin,
Thank you for your contributions. Unfortunately, I will need to roll back to version 82e5f06 from Nov 6, 2016 after having tested your patches. The reason is that T2WS and the application that embeds it are freezing after applying your patches. I have checked that by using simply one of the demos that are part of the T2WS package. I used Firefox and Edge for the tests. Both browsers don't add the 'Content-Length' header to the request and they also don't close the connection (they keep it alive). Firefox for example provides the following headers:
```
GET / HTTP/1.1
Host: localhost:8080
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Upgrade-Insecure-Requests: 1
```
This means that the following loop will never end:
```
while {![eof $Socket]} {
   append RequestBody [read $Socket]
}
```
Also the solution to check if the content-length header is available will not work, since it is not available. Also in this case the read loop is executed forever:
```
if {[dict exists $RequestHeader content-length]} {
   set contentLength [dict get $RequestHeader content-length]
   while {![eof $Socket]} {
      if {[string bytelength $RequestBody] >= $contentLength} { break }
      append RequestBody [read $Socket $contentLength]
   }
} else {
   while {![eof $Socket]} {
      append RequestBody [read $Socket]
   }
}
```
It is not clear to me what is the best solution that works for any browsers. Using the content-length header when it is available seems be a good one. But in any cases there should be a timeout that is considered.

Let me know if you see a good solution.

Thanks,
Andreas

**Comment by rmweiss** [comment]
I did see the same endless loop after applying the patch from the 1. of April, but wasn't sure if it was a problem on my part.

After reading a bit more, it seems that the waiting for the end of the connection does only work for the client side of the HTTP connection, because the server doesn't close the connection but sends a response.

I think this should be the correct guide how to handle message bodies: 
https://tools.ietf.org/html/rfc2616#section-4.4

(But I think that an additional timeout in case of misbehaving clients is also a good idea)

**Comment by Drolla** [comment]
Hi @rmweiss and @Geballin ,
What do you think about the following patch?

```
# Read the body until one of the following conditions becomes true:
# 1) socket is closed, 2) no more data is available, 3) the size of 
# the received body matches the content-length header.
# See also https://tools.ietf.org/html/rfc2616#section-4.4
set RequestBody {}
while {![eof $Socket]} {
	set Chunk [read $Socket]
	if {$Chunk==""} {
		break }
	append RequestBody $Chunk
	if {[dict exists $RequestHeader content-length] &&
	    [string bytelength $RequestBody]>=[dict get $RequestHeader content-length]} {
		break }
	after 1; # Is this statement required?
}
```
It continuous reading if some body data could be read until the socket is closed or until the expected body length is achieved.
The _after_ statement gives some time to fill up the buffer again once it has been read. I don't like this statement (since waiting is never efficient), but I am not sure if it can be omitted.
I did some minimal testing, but it would be good if it could be checked with @Geballin 's test case that has huge body data.
Regards,
Andreas

**Comment by rmweiss** [comment]
I don't like the loop until EOF without checking for content-length or tranfer-encoding first.

RFC7230 seems to replace RFC2616, so the current way to read the body correctly is probably: https://greenbytes.de/tech/webdav/rfc7230.html#message.body.length

IF I understand this correctly (which is a big if), then you can assume that messages without content-length or a transfer-encoding which ends with "chunked" do not contain a body.

Probably you would have to implement the processing of "chunked transfer coding", because otherwise the server would not be HTTP/1.1 compatible. 

It might be a possibility to (for the moment) return the status "501 Not Implemented" and a suitable explanation in the body if you get the body as "Chunked Transfer Coding". 
Then the client at least has the possibility to find out what the problem is.

Regards,
René

**Comment by Geballin** [comment]
Hi @Drolla and @rmweiss 
I saw the problem when testing with a simple curl, It doesn't close the socket...

So, just made that simple testing server : 

    ### This is the server side for the test of getting big body

    # To add the path where to find t2ws
    lappend auto_path [file join [ file dirname [ file normalize [ info script ] ] ] {..}]

    package require Tcl 8.6
    package require t2ws
    package require fileutil

    proc myResponder {Request} {
        puts "Received request"
        if {[string compare [dict get $Request Body] [fileutil::cat [string range [dict get $Request URI] 1 end]]]} {
        	return [dict create Status 500 Body "Body is different than expected"]}
        return [dict create Body "Request OK"]
     }

    t2ws::Start 2999 -responder ::myResponder
    vwait forever

Call it now with a curl with a big file (4.2MO in my test) : 
`curl http://localhost:2999/bigfile.xml -X POST --data-binary @bigfile.xml`

Concerning your patch @Drolla , you must remove the part

    	if {$Chunk==""} {
		break }

to make it work because when receiving big file, the first reads on the socket channel are empty, so with your patch, Body of big files is always {} .
`after 1` doesn't look to do anything, so I think it's better to remove it while waiting for more tests.

Finaly the code that work for my test using curl is : 

		# Read the Body (if the header section was read successfully)
		if {$State=="Body"} {
			set RequestBody {}
		    while {![eof $Socket]} {
			set Chunk [read $Socket]
			append RequestBody $Chunk
			if {[dict exists $RequestHeader content-length] &&
			    [string bytelength $RequestBody]>=[dict get $RequestHeader content-length]} {
			    break }
		    }
		}

But that need more tests using other tools and browser. Could be interested to test what's happening when streaming file (so no content-length).

I agree with @rmweiss concerning the fact there should have been content-length or a transfer-encoding which ends with "chunked". But a real test with different clients should be very relevant.

**Comment by rmweiss** [comment]
Here the current status of my attempt to solve the problem:

```Tcl
if {$State=="Body"} {

	set RequestBody {}

	set transfer_encoding {}
	if {[dict exists $RequestHeader transfer-encoding]} {
		set transfer_encoding [dict get $RequestHeader transfer-encoding]
	}

	# RFC7230 - 3.3.3. Message Body Length
	# If a Transfer-Encoding header field is present and the chunked
	# transfer coding (Section 4.1) is the final encoding, the message
	# body length is determined by reading and decoding the chunked
	# data until the transfer coding indicates the data is complete.
	if {[string match {*chunked} $transfer_encoding]} {

		while {![eof $Socket]} {

			set chunk_header {}

			while {$chunk_header == {}} {
				gets $Socket chunk_header
			}

			# The chunk header can include "chunk extensions" after a semicolon
			set chunk_size_hex [lindex [split $chunk_header {;}] 0]
			set chunk_size [expr 0x$chunk_size_hex]
			
			if {$chunk_size == 0} { break }

			set current_chunk {}

			while {![eof $Socket]} {
				if {[string bytelength $current_chunk] >= $chunk_size} { break }
				append current_chunk [read $Socket $chunk_size]
			}

			append RequestBody $current_chunk
		}

		#dict set Response ErrorStatus 501
		#dict set Response ErrorBody {Chunked transfer encoding not supported}
		#Log {Chunked transfer encoding not supported} info 2
	} elseif {[dict exists $RequestHeader content-length]} {
		set contentLength [dict get $RequestHeader content-length]

		while {![eof $Socket]} {
			if {[string bytelength $RequestBody] >= $contentLength} { break }
			append RequestBody [read $Socket $contentLength]
		}

	} else {
		# No "content-length" and not "transfer-encoding" doesn't end
		# in "chunked". So there should be no body.
	}

	if {$RequestBody!=""} {
		Log {$RequestBody} input 3 
	}
}
```

**Comment by Geballin** [comment]
@rmweiss Quickly tested, it works.
Will see for more tests soon.

**Comment by Drolla** [comment]
Hello,
Thank you for your implementation suggestion, @rmweiss. On a first glance it looks good and also my initial tests and my application that don't receive any body data work well.

However, using @Geballin 's Curl command that uses the body to upload the content of a file, my T2WS server as well as Curl were hanging. I had to kill Curl to unfreeze the T2WS server again. The transcript I have received is here:
```
_HttpServer::Start 8080_
_HttpServer::Accept sock896 127.0.0.1 64620_
_HttpServer::SocketService sock896 (port 8080)_
POST /my_test_file.txt HTTP/1.1
Host: localhost:8080
User-Agent: curl/7.55.1
Accept: */*
Content-Length: 47
Content-Type: application/x-www-form-urlencoded

_Received body length: 46_
Hello, this is my test file.
It is very short.
```
It turned out that my file uses Windows line endings ("\r\n") that contain two characters. The read command translates them into a single newline character (translation: auto crlf), which ends up with a string length that was smaller than the content-length header. The read loop couldn't reach an end. The body needs therefore to be read in binary mode.

I have added the binary translation configuration to the code provided by @rmweiss and did also some style changes. I am not saying that the style used in the added code is incorrect, but the mix of the original _CamelCase_ style and the new _lower_case_with_underscores_ style made the code looking really ugly. I hope you agree with this cosmetic change.
The new code is:
```Tcl
# Read the Body (if the header section was read successfully)
if {$State=="Body"} {
	set RequestBody {}
	
	# Read the body in binary mode to match the content length and avoid
	# any unwanted translation of binary data
	fconfigure $Socket -translation {binary crlf}

	set TransferEncoding ""
	if {[dict exists $RequestHeader transfer-encoding]} {
		set TransferEncoding [dict get $RequestHeader transfer-encoding]
	}

	# RFC7230 - 3.3.3. Message Body Length
	# If a Transfer-Encoding header field is present and the chunked
	# transfer coding (Section 4.1) is the final encoding, the message
	# body length is determined by reading and decoding the chunked
	# data until the transfer coding indicates the data is complete.
	if {[string match {*chunked} $TransferEncoding]} {
		while {![eof $Socket]} {
			set ChunkHeader ""
			while {$ChunkHeader==""} {
				gets $Socket ChunkHeader
			}

			# The chunk header can include "chunk extensions" after a semicolon
			set ChunkSizeHex [lindex [split $ChunkHeader {;}] 0]
			set ChunkSize [expr 0x$ChunkSizeHex]
			if {$ChunkSize==0} {
				break}

			set CurrentChunk {}
			while {![eof $Socket]} {
				if {[string bytelength $CurrentChunk]>=$ChunkSize} {
					break}
				append CurrentChunk [read $Socket $ChunkSize]
			}

			append RequestBody $CurrentChunk
		}

		#dict set Response ErrorStatus 501
		#dict set Response ErrorBody {Chunked transfer encoding not supported}
		#Log {Chunked transfer encoding not supported} info 2
	} elseif {[dict exists $RequestHeader content-length]} {
		# Read the number of bytes defined by the content-length header
		set ContentLength [dict get $RequestHeader content-length]
		while {![eof $Socket]} {
			if {[string bytelength $RequestBody]>=$ContentLength} {
				break}
			append RequestBody [read $Socket $ContentLength]
		}
	
	} else {
		# No "content-length" and not "transfer-encoding" doesn't end
		# in "chunked". So there should be no body.
	}

	# Switch back to the standard translation mode
	fconfigure $Socket -translation {auto crlf}

	if {$RequestBody!=""} {
		Log {Received body length: [string bytelength $RequestBody]} info 3 
		Log {$RequestBody} input 3
	}
}
```
Please test the code. Once it works for you, would you like to submit a new pull request, @rmweiss. Or should I just update it in the repository?

**Pull request closed without merging**
